#!/bin/bash

PATH=$HOME/scala-2.10.3/bin:$PATH
PATH=$HOME/bin:$PATH
PATH=~/android/sdk/tools:$PATH
PATH=~/android/sdk/platform-tools:$PATH
PATH=/usr/local/Cellar/ruby/2.1.2/bin:$PATH
export PATH

PYTHONPATH=/usr/local/lib/python2.7/site-packages
export PYTHONPATH

export JAVA_HOME=$(/usr/libexec/java_home)
export HADOOP_HOME=$HOME/hadoop/
export MAHOUT_HOME=$HOME/mahout/
# export SCALA_HOME=$(brew --repository)/Library/LinkedKegs/scala/libexec
export SCALA_HOME=$(/usr/local/bin/brew --prefix scala)/libexec
export TEXMFHOME=$HOME/repos/latex

export SHELL=/usr/local/bin/bash
