#!/bin/bash

PATH=$HOME/bin:$PATH
PATH=$HOME/scala-2.9.1.final/bin:$PATH
PATH=/opt/local/bin:$PATH
PATH=/opt/local/sbin:$PATH
PATH=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH
export PATH
 PYTHONPATH=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages
export JAVA_HOME=$(/usr/libexec/java_home)
export HADOOP_HOME=$HOME/hadoop/
export MAHOUT_HOME=$HOME/mahout/
export SCALA_HOME=$HOME/scala-2.9.1.final/
export TEXMFHOME=$HOME/repos/latex
