#!/bin/bash

PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export PATH

PYTHONPATH=/usr/local/lib/python2.7/site-packages:$HOME/.local/lib/python2.7/site-packages
export PYTHONPATH

export JAVA_HOME=$(/usr/libexec/java_home)
export HADOOP_HOME=$HOME/hadoop/
export MAHOUT_HOME=$HOME/mahout/
# export SCALA_HOME=$(brew --repository)/Library/LinkedKegs/scala/libexec
export SCALA_HOME=$(/usr/local/bin/brew --prefix scala)/libexec
export TEXMFHOME=$HOME/repos/latex

export SHELL=/usr/local/bin/bash
