tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/gui'
tap 'homebrew/head-only'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/x11'
tap 'railwaycat/emacsmacport'
tap 'ankurdave/ankurdave'

cask 'mactex'
cask 'java'

brew 'ankurdave/ankurdave/afew', args: ['HEAD']
brew 'aspell', args: ['with-lang-en']
brew 'automake'
brew 'bash'
brew 'bash-completion'
brew 'cmake'
brew 'coreutils'
brew 'fdupes'
brew 'figlet'
brew 'gcc'
brew 'ghostscript'
brew 'git'
brew 'git-number'
brew 'global', args: ['with-ctags', 'with-pygments', 'with-sqlite3']
brew 'gnuplot', args: ['with-cairo', 'with-pdflib-lite', 'with-tex', 'with-wxmac']
brew 'homebrew/gui/inkscape'
brew 'htop'
brew 'imagemagick'
brew 'isync'
brew 'matplotlib'
brew 'maven'
brew 'mercurial'
brew 'ncdu'
brew 'notmuch'
brew 'numpy'
brew 'optipng'
brew 'pandoc'
brew 'parallel'
brew 'python'
brew 'python3'
brew 'railwaycat/emacsmacport/emacs-mac', args: ['with-gnutls', 'with-official-icon']
brew 'rsnapshot'
brew 's3cmd'
brew 'sbt'
brew 'scala'
brew 'sctags', args: ['HEAD']
brew 'wget'

cask 'backblaze'
cask 'darktable'
cask 'dropbox'
cask 'flux'
cask 'font-roboto'
cask 'gimp'
cask 'google-chrome'
cask 'google-photos-backup'
cask 'iterm2'
cask 'keepassx'
cask 'lumen'
cask 'microsoft-office'
cask 'omnigraffle'
cask 'skim'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'viber'
cask 'virtualbox'
cask 'vlc'
cask 'yakyak'
