#!/bin/bash

pushd ~
if [[ ! -e history ]]
then
    git init history
fi
popd

find $(cd $(dirname $0) && pwd) -mindepth 1 -maxdepth 1 -not \( -iname '*~' -or -iname '*#*' -or -iname '.hg' -or -iname '.git' -or -iname '.gitmodules' -or -iname 'setup' \) -exec bash -c \
    "TARGET=~/\$(basename {})
     echo \"Looking at \$TARGET\"
     if [[ -e \$TARGET && ! -L \$TARGET ]]
     then
         mkdir -p ~/config-old/
         mv \$TARGET ~/config-old/
     fi

     if [[ -L \$TARGET ]]
     then
         rm \$TARGET
     fi

     ln -s {} \$TARGET" \;