#!/bin/bash

case $(hostname -f | tr '[A-Z]' '[a-z]') in
    ankur-laptop)
        CONFIGDIR=ankur-laptop
        ;;
    *.cs.berkeley.edu)
        case $(uname) in
            Darwin)
                CONFIGDIR=inst-mac
                ;;
            Linux)
                CONFIGDIR=inst-linux
                ;;
            *)
                CONFIGDIR=inst
                ;;
        esac
        ;;
    r*.millennium.berkeley.edu)
        CONFIGDIR=r-cluster
        ;;
    *)
        ;;
esac

ACTION=$1
if [[ -e ~/.bashrc.d/local/$CONFIGDIR/$ACTION ]]; then
    . ~/.bashrc.d/local/$CONFIGDIR/$ACTION
fi