#!/bin/bash

case $(hostname -f | tr '[A-Z]' '[a-z]') in
    ankur*)
        case $(uname) in
            Darwin)
                CONFIGDIR=ankur-laptop-mac
                ;;
            Linux)
		CONFIGDIR=ankur-laptop
                ;;
        esac
        ;;
    dave-server)
        CONFIGDIR=dave-server
        ;;
    *.cs.berkeley.edu)
        case $(uname) in
            Darwin)
                CONFIGDIR=inst-mac
                ;;
            Linux)
                CONFIGDIR=inst-linux
                ;;
            *)
                CONFIGDIR=inst
                ;;
        esac
        ;;
    r*.millennium.berkeley.edu)
        CONFIGDIR=r-cluster
        ;;
    ip-*.ec2.internal)
        CONFIGDIR=ec2
        ;;
    *.corp.google.com)
        CONFIGDIR=google
        ;;
    *.amazon.com)
	CONFIGDIR=amazon
	;;
    *)
        ;;
esac

ACTION=$1
if [[ -e ~/.bashrc.d/local/$CONFIGDIR/$ACTION ]]; then
    . ~/.bashrc.d/local/$CONFIGDIR/$ACTION
fi
