(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-master 'dwim)
 '(TeX-save-query nil)
 '(TeX-source-correlate-mode t)
 '(TeX-view-program-list
   '(("open" "/Applications/Skim.app/Contents/SharedSupport/displayline -g %n %o %b")))
 '(TeX-view-program-selection
   '(((output-dvi style-pstricks)
      "dvips and gv")
     (output-dvi "xdvi")
     (output-pdf "open")
     (output-html "xdg-open")))
 '(ansi-color-for-comint-mode t)
 '(ansi-color-names-vector
   ["#2e3436" "#a40000" "#4e9a06" "#c4a000" "#204a87" "#5c3566" "#729fcf" "#eeeeec"])
 '(c-default-style
   '((c++-mode . "google")
     (java-mode . "java")
     (awk-mode . "awk")
     (other . "gnu")))
 '(compilation-scroll-output 'first-error)
 '(copilot-indent-warning-suppress t)
 '(copilot-log-max 10000)
 '(cursor-type '(bar . 2))
 '(custom-safe-themes
   '("f56eb33cd9f1e49c5df0080a3e8a292e83890a61a89bceeaa481a5f183e8e3ef" default))
 '(default-input-method "TeX")
 '(delete-by-moving-to-trash t)
 '(delete-selection-mode t)
 '(electric-indent-mode t)
 '(enable-recursive-minibuffers t)
 '(ffap-machine-p-known 'reject)
 '(fill-column 80)
 '(find-function-recenter-line nil)
 '(fringe-mode 0 nil (fringe))
 '(help-window-select t)
 '(history-length 500)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(load-prefer-newer t t)
 '(menu-bar-mode nil)
 '(message-citation-line-format "At %Y-%m-%d %T %z, %f wrote:")
 '(message-citation-line-function 'message-insert-formatted-citation-line)
 '(message-cite-reply-position 'traditional)
 '(message-cite-style nil)
 '(message-confirm-send t)
 '(message-fill-column nil)
 '(minibuffer-depth-indicate-mode t)
 '(ns-alternate-modifier 'meta)
 '(ns-command-modifier 'meta)
 '(org-agenda-files '("~/Dropbox/ls400/ls400-service.org"))
 '(package-selected-packages
   '(treesit string-inflection editorconfig copilot explain-pause-mode beancount auto-compile adaptive-wrap quelpa-use-package auto-package-update zenburn-theme ws-butler which-key web-mode undo-tree auctex terraform-mode sql-indent smex scala-mode rainbow-mode protobuf-mode php-mode paren-face paredit markdown-mode magit lisp-extra-font-lock ivy-rich htmlize highlight-symbol google-c-style gnuplot-mode flx expand-region edit-server dumb-jump dtrt-indent dockerfile-mode diminish dash cuda-mode csv-mode counsel-projectile counsel))
 '(pop-up-windows t)
 '(recentf-max-saved-items 200)
 '(require-final-newline t)
 '(safe-local-variable-values
   '((eval add-hook 'before-save-hook 'sort-package-configurations nil t)
     (eval add-to-list 'before-save-hook 'sort-package-configurations)))
 '(scroll-bar-mode nil)
 '(select-enable-clipboard t)
 '(send-mail-function 'smtpmail-send-it)
 '(sentence-end-double-space nil)
 '(show-paren-delay 0.0)
 '(show-paren-mode t)
 '(smtpmail-smtp-server "smtp.gmail.com")
 '(smtpmail-smtp-service 465)
 '(smtpmail-stream-type 'ssl)
 '(split-height-threshold 100)
 '(split-width-threshold 200)
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(user-full-name "Ankur Dave")
 '(user-mail-address "ankurdave@gmail.com")
 '(vc-follow-symlinks t)
 '(vc-handled-backends nil)
 '(visible-bell nil)
 '(visual-line-mode nil t)
 '(warning-suppress-log-types
   '(((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))))
 '(warning-suppress-types
   '(((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))))
 '(word-wrap t)
 '(xterm-mouse-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(highlight-symbol-face ((t (:background "black" :foreground "yellow"))))
 '(ivy-current-match ((t (:background "#4F4F4F" :foreground "#F0DFAF" :underline nil :weight normal)))))
